#!/bin/bash
PATH=$HOME/Prakash/BenTest/bin/D2:$PATH
#echo "path  $PATH"
#echo "`which llc`"
for  oclf in *.cl
do
#oclf=add.cl
fname=`echo "$oclf" | cut -d'.' -f1`
echo " Compiling $fname "
clc2 -cl-std=CL2.0 $oclf -o results/$fname.fe.bc
#llvm-dis  -o results/$fname.fe.ll results/$fname.fe.bc
#clc  --support_all_extension --opencl=1.2 -o results/$fname.fe.ll $oclf
#llvm-as  -o results/$fname.fe.bc results/$fname.fe.ll
echo "FE complete"
llvm-link -o results/$fname.linked.bc results/$fname.fe.bc -l $HOME/Prakash/BenTest/bin/D2/builtins-hsail.bc
echo "llvm-link completed!"
#llvm-dis  -o results/$fname.linked.ll results/$fname.linked.bc
opt  -O3 -whole -gpu results/$fname.linked.bc -o results/$fname.opt.bc
echo "opt complete!"
#llvm-dis  -o results/$fname.opt.ll results/$fname.opt.bc
llc  -O2 -march=hsail-64 -o results/$fname.brig  results/$fname.opt.bc
echo "llc complete"
hsailasm  -disassemble -o results/$fname.hsail  results/$fname.brig
echo "HSAIL generated!"
echo ""
#Dev  -int_disassembler -ns -Q -Bonaire -d -brig  results-conformance/$fname.brig 
done
